---
title: "NetSciX_2016_Workshop"
author: "David Tsai"
date: "3/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reading network data from files
# Dataset 1: edgelist
```{r}
nodes = read.csv("dataset/Dataset1-Media-Example-NODES.csv", header = T, as.is = T)
edges = read.csv("dataset/Dataset1-Media-Example-EDGES.csv", header = T, as.is = T)

head(nodes)
head(edges)

nrow(nodes)
length(unique(nodes$id))

nrow(edges)
nrow(unique(edges[,c("from", "to")]))
```


Collapse all links of the same type between the same two nodes by summing their weights, using aggregate() by “from”, “to”, & “type”. 
```{r}
edges = aggregate(edges[,3], edges[,-3], sum)
edges = edges[order(edges$from, edges$to),]
colnames(edges)[4] = "weight"
rownames(edges) = NULL
head(edges)
```


# Dataset 2: matrix
```{r}
nodes_user = read.csv("dataset/Dataset2-Media-User-Example-NODES.csv", header = T, 
                      as.is = T)
edges_user = read.csv("dataset/Dataset2-Media-User-Example-EDGES.csv", header = T, 
                      row.names = 1)

head(nodes_user)
head(edges_user)
```

```{r}
edges_user = as.matrix(edges_user)
dim(edges_user)
```


## Turning networks into igraph objects
# Dataset 1
```{r}
library(igraph)
net = graph_from_data_frame(d = edges, vertices = nodes, directed = T)
class(net)
```

Make a plot
```{r}
plot(net, edge.arrow.size = .5, vertex.label = NA)
```

Removing the loops in the graph
```{r}
net = simplify(net, remove.multiple = F, remove.loops = T)
plot(net, edge.arrow.size = .5, vertex.label = NA)
```

# Dataset 2
```{r}
net2 = graph_from_incidence_matrix(edges_user)
table(V(net2)$type)

net2.bp = bipartite.projection(net2)
#calculate the projections
proj = as_incidence_matrix(net2) %*% t(as_incidence_matrix(net2))
proj2 = t(as_incidence_matrix(net2)) %*% as_incidence_matrix(net2)
```

Make plots
```{r}
plot(net2.bp$proj1, vertex.label.color = "black", vertext.label.dist = 1,
     vertex.size = 7, vertex.label = nodes_user$media[!is.na(nodes_user$media.type)])

plot(net2.bp$proj2, vertex.label.color = "black", vertext.label.dist = 1,
     vertex.size = 7, vertex.label = nodes_user$media[is.na(nodes_user$media.type)])
```

```{r}
# plot with curved edges and reduce arrow size
plot(net, edge.arrow.size = .5, edge.curved = .1)
```

```{r}
# set edge color to gray, and node color to orange.
# replace the vertex label with the node names stored in "media"
plot(net, edge.arrow.size = .3, edge.curved = 0,
vertex.color = "orange", 
vertex.frame.color = "#555555", 
vertex.label = V(net)$media, 
vertex.label.color="black", 
vertex.label.cex=.7)
```

Plot only the labels of the nodes
```{r}
plot(net, vertex.shape = "none", 
     ertex.label = V(net)$media, 
     vertex.label.font = 3, 
     vertex.label.color = "gray40", 
     vertex.label.cex = .7, 
     edge.color = "gray85")
```